export enum EnterpriseSpecialty {
    CLINICA_ESTETICA = "Clínica Estética",
    CLINICA_TERAPEUTICA = "Clínica Terapêutica",
    CLINICA_ODONTOLOGICA = "Clínica Odontológica",
    CLINICA_FISIOTERAPIA = "Clínica de Fisioterapia",
    CLINICA_PODOLOGIA = "Clínica de Podologia",
    CLINICA_VETERINARIA = "Clínica Veterinária",
    CONSULTORIO_PSICOLOGIA = "Consultório de Psicologia",
    CONSULTORIO_NUTRICAO = "Consultório de Nutrição",
    BARBEARIA = "Barbearia",
    SALAO_BELEZA = "Salão de Beleza",
    MANICURE_PEDICURE = "Serviços de Manicure e Pedicure",
    DEPILACAO = "Serviços de Depilação",
    SPA = "SPA e Bem-estar",
    ESTUDIO_TATUAGEM = "Estúdio de Tatuagem",
    ESTUDIO_PIERCING = "Estúdio de Piercing",
    ESTUDIO_FOTOGRAFIA = "Estúdio de Fotografia",
    YOGA_PILATES = "Estúdio de Yoga e Pilates",
    PERSONAL_TRAINER = "Personal Trainer",
    COACHING = "Serviço de Coaching",
    CONSULTORIA = "Serviço de Consultoria",
    AUTOESCOLA = "Autoescola",
    ESCOLA_MUSICA = "Escola de Música",
    ESCOLA_IDIOMAS = "Escola de Idiomas",
    AULAS_PARTICULARES = "Aulas Particulares",
    PETSHOP = "Petshop com Serviços",
    SERVICO_TECNICO = "Serviço Técnico com Agendamento",
    ADVOCACIA = "Escritório de Advocacia",
    CONTABILIDADE = "Escritório de Contabilidade",
    IMOBILIARIA = "Imobiliária (com visitas agendadas)",
    STUDIO_MASSAGEM = "Estúdio de Massagem",
    TERAPIA_OCUPACIONAL = "Consultório de Terapia Ocupacional",
}

export const enterpriseSpecialty = Object.entries(EnterpriseSpecialty).map(
    ([key, value]) => ({
        value: EnterpriseSpecialty[key as keyof typeof EnterpriseSpecialty],
        label: value,
    }),
);
